#!/usr/bin/env zsh

IMAGE_AND_VERSION=$(vw/installed-images-and-versions | jq -r '.[] | .name as $name | .versions[] | "\($name) \(.)"' | rofi -dmenu -no-custom -i -p "Open directory of Visualworks Image" -lines 20)
[ -n "$IMAGE_AND_VERSION" ] || exit 1

IMAGE=${IMAGE_AND_VERSION% *}
VERSION=${IMAGE_AND_VERSION#* }

cd $(vw/dir $IMAGE $VERSION) && x-terminal-emulator &