#!/usr/bin/env zsh

IMAGE_AND_VERSION=$(vw/installed-images-and-versions | jq -r '.[] | .name as $name | .versions[] | "\($name) \(.)"' | rofi -dmenu -no-custom -i -multi-select -p "Uninstall Visualworks Image(s)" -lines 20)
[ -n "$IMAGE_AND_VERSION" ] || exit 1

for i in ${(f)IMAGE_AND_VERSION} ; do
    IMAGE=${i% *}
    VERSION=${i#* }
    vw/uninstall-image-version $IMAGE $VERSION
done

