name: Build and Push Docker Images

on:
  push:
    tags:
      - release-[0-9]+.[0-9]+.[0-9]+[a-z]*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract version from tag
        id: tagName
        uses: olegtarasov/get-tag@v2.1
        with:
          tagRegex: release-([0-9]+.[0-9]+.[0-9]+[a-z]*)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push vw image
        uses: docker/build-push-action@v3
        with:
          context: ./vw
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION_TAG=${{ steps.tagName.outputs.tag }}
          push: true
          tags: soopsnl/devanyware-vw:${{ steps.tagName.outputs.tag }}
